name: Build and Release

on: [push]

env:
  go-version: 1.26.x
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Setup Go ${{ env.go-version }}
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '${{ env.go-version }}'
      - name: Install dependencies
        run: go get ./cmd/screeps-launcher
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
      - name: Upload sample
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: config-sample
          path: ./config.sample.yml
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm, arm64]
        exclude:
        - os: windows
          arch: arm
        - os: darwin
          arch: arm
        - os: darwin
          arch: arm64
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Setup Go ${{ env.go-version }}
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '${{ env.go-version }}'
      - name: Install dependencies
        run: go get ./cmd/screeps-launcher
      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ./screeps-launcher_${{ matrix.os }}_${{ matrix.arch }} ./cmd/screeps-launcher
      - name: Upload binary
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: screeps-launcher-${{ matrix.os }}-${{ matrix.arch }}
          path: ./screeps-launcher_${{ matrix.os }}_${{ matrix.arch }}
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          merge-multiple: true
      - name: Rename Windows Files
        run: for F in screeps-launcher_windows*; do mv $F $F.exe; done
      - name: Create release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        with:
          files: |
            screeps-launcher*
            config.sample.yml
